import { Text } from "react-native-gesture-handler";

export const GlobalColors = {
    light:{
       
        primary: '#000',
        secondary: '#6c757d',
        success: '#28a745',
        danger: '#dc3545',
        warning: '#ffc107',
        info: '#17a2b8',
        light: '#f8f9fa',
        dark: '#343a40',
        bg: '#fff',
        subbg:'#fff',
        overbg:'#b0b0b0',
        gold: '#FFD700',
        border: '#D3D3D3',
        border1: '#6c757d',
        bar:'#000',
        text:'#000',
        select:'red',
        new:'#fff',
        bgc:'#D0D0D0',
        dis:'#E8E3FC',
        point:'#F5F3FF',
        line:'#000',
        box:'#EEEE',
    },
    dark:{
        primary: '#fff',
        secondary: '#6c757d',
        success: '#198754',
        danger: '#dc3545',
        warning: '#ffc107',
        info: '#0dcaf0',
        light: '#f8f9fa',
        dark: '#212529',
        bg: '#000',
        subbg:'#2A2A2A',
        overbg:'#2A2A2A',
        gold: '#ffd700',
        border: '#6c757d',
        border1: '#BFC3C5',
        bar:'#2A2A2A',
        text:'#fff',
        select:'red',
        new:'#fff',
        bgc:'#000',
        dis:'#514a5c',
        point:'#000',
        line:'#2A2A2A',
        box:'#000',
     
    }
}